global using Xunit;
global using Microsoft.Extensions.Localization;
global using Moq;
global using Nest;
global using Provider.Configuration;
global using Provider.Types.Entities;
global using Provider.Types.Repositories;
global using Provider.Results;
global using Test.Entities;